# Generated by Django 3.0.3 on 2020-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_no', models.CharField(max_length=20)),
                ('cer_no', models.CharField(max_length=20)),
                ('date_recieved', models.CharField(max_length=20)),
                ('date_assigned', models.CharField(max_length=20)),
                ('complaint_name', models.CharField(max_length=20)),
                ('complaint_address', models.CharField(max_length=20)),
                ('complaint_soo', models.CharField(max_length=20)),
                ('complaint_lga', models.CharField(max_length=20)),
                ('complaint_sex', models.CharField(choices=[('S', 'Select'), ('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('complaint_age', models.IntegerField(max_length=4)),
                ('suspect_name', models.CharField(max_length=20)),
                ('suspect_address', models.CharField(max_length=20)),
                ('suspect_soo', models.CharField(max_length=20)),
                ('suspect_lga', models.CharField(max_length=20)),
                ('suspect_sex', models.CharField(choices=[('S', 'Select'), ('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('suspect_age', models.IntegerField(max_length=4)),
                ('offence', models.CharField(max_length=20)),
                ('amount_involved_naira', models.IntegerField()),
                ('amount_involved_dollar', models.IntegerField()),
                ('cfa_involved', models.CharField(max_length=20)),
                ('others_involved', models.CharField(max_length=20)),
                ('amount_recieved_naira', models.IntegerField()),
                ('amount_recieved_dollar', models.IntegerField()),
                ('cfa_recieved', models.CharField(max_length=20)),
                ('others_recieved', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('date_sent_to_legal', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
