# Generated by Django 3.0.3 on 2020-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0003_auto_20200205_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecord',
            name='complaint_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createrecord',
            name='suspect_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
