# Generated by Django 3.0.3 on 2020-02-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0004_auto_20200205_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createrecord',
            old_name='cFA_recieved',
            new_name='cfa_recieved',
        ),
        migrations.RenameField(
            model_name='createrecord',
            old_name='suspect_state_of_orgin',
            new_name='suspect_state_of_origin',
        ),
    ]
