# Generated by Django 3.0.3 on 2020-02-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0007_auto_20200213_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecord',
            name='complaint_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='createrecord',
            name='suspect_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
